name: segmentacion-artistas
channels:
  - conda-forge
  - plotly
  - nvidia
  - anaconda
  - rapidsai
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - anyio=4.9.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - astroid=3.3.9
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - autopep8=2.0.4
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.0
  - aws-c-common=0.12.2
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.10.0
  - aws-c-io=0.18.1
  - aws-c-mqtt=0.12.3
  - aws-c-s3=0.7.16
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.4
  - aws-sdk-cpp=1.11.510
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - cffi=1.17.1
  - click=8.1.8
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.0
  - cpython=3.9.23
  - cycler=0.12.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dill=0.4.0
  - docstring-to-markdown=0.17
  - docutils=0.21.2
  - exceptiongroup=1.2.2
  - executing=2.2.0
  - flake8=7.1.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fqdn=1.5.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - getopt-win32=0.1
  - graphite2=1.3.13
  - graphviz=12.2.1
  - gts=0.7.6
  - h11=0.16.0
  - h2=4.2.0
  - harfbuzz=11.1.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - intel-openmp=2024.2.1
  - ipykernel=6.30.1
  - ipython=8.18.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - isort=6.0.1
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.6
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.6
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lark=1.2.2
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.1
  - libarrow=20.0.0
  - libarrow-acero=20.0.0
  - libarrow-dataset=20.0.0
  - libarrow-substrait=20.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.13.0
  - libdeflate=1.23
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgd=2.3.3
  - libglib=2.84.1
  - libgomp=15.1.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.71.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libparquet=20.0.0
  - libpng=1.6.47
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.10.0
  - libwebp-base=1.5.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - markdown=3.8
  - markupsafe=3.0.2
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.1.7
  - mccabe=0.7.0
  - mistune=3.1.3
  - mkl=2024.2.2
  - munkres=1.1.4
  - narwhals=1.38.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - nodejs=22.13.0
  - notebook=7.4.5
  - notebook-shim=0.2.4
  - openjpeg=2.5.3
  - openssl=3.5.0
  - orc=2.1.1
  - overrides=7.7.0
  - packaging=25.0
  - pandocfilters=1.5.0
  - pango=1.56.3
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.45
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1
  - pixman=0.46.0
  - platformdirs=4.3.7
  - plotly=6.3.0
  - pluggy=1.5.0
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pyarrow=20.0.0
  - pyarrow-core=20.0.0
  - pycodestyle=2.12.1
  - pycparser=2.22
  - pycrdt=0.11.1
  - pydocstyle=6.3.0
  - pydot=4.0.0
  - pyflakes=3.2.0
  - pygments=2.19.1
  - pylint=3.3.7
  - pymdown-extensions=10.15
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.9.22
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.12.2
  - python-lsp-server-base=1.12.2
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytoolconfig=1.2.5
  - pytz=2025.2
  - pywinpty=2.0.15
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - qhull=2020.2
  - qrcode=8.2
  - re2=2024.07.02
  - referencing=0.36.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rope=1.13.0
  - ruff=0.11.8
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=79.0.1
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - snowballstemmer=2.2.0
  - soupsieve=2.7
  - stack_data=0.6.3
  - starlette=0.46.2
  - statsmodels=0.14.4
  - tbb=2021.13.0
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tomlkit=0.13.2
  - tornado=6.5.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250809
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - typing_utils=0.1.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - ujson=5.10.0
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - uvicorn=0.34.2
  - vc=14.3
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=15.0.1
  - whatthepatch=1.0.7
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxpm=3.5.17
  - xorg-libxt=1.3.1
  - yaml=0.2.5
  - yapf=0.43.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - altair==5.5.0
      - annotated-types==0.7.0
      - arro3-core==0.4.6
      - async-timeout==5.0.1
      - cattrs==24.1.3
      - certifi==2025.4.26
      - charset-normalizer==3.4.1
      - choreographer==1.0.10
      - commonmark==0.9.1
      - distro==1.9.0
      - duckdb==1.2.2
      - faicons==0.2.2
      - fastjsonschema==2.21.1
      - fonttools==4.58.0
      - gensim==4.3.3
      - great-tables==0.17.0
      - htmltools==0.6.0
      - iniconfig==2.1.0
      - jiter==0.9.0
      - joblib==1.5.1
      - jsonschema==4.23.0
      - jupyter-core==5.7.2
      - kaleido==1.0.0
      - logistro==1.1.0
      - loro==1.5.0
      - lsprotocol==2023.0.1
      - marimo==0.15.2
      - networkx==3.2.1
      - node2vec==0.5.0
      - numpy==1.26.4
      - openai==1.77.0
      - orjson==3.11.3
      - pandas==2.2.3
      - polars==1.29.0
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pytest==8.3.5
      - python-lsp-ruff==2.2.2
      - pywin32==310
      - redis==5.2.1
      - requests==2.32.3
      - rpds-py==0.24.0
      - scikit-learn==1.6.1
      - simplejson==3.20.1
      - smart-open==7.1.0
      - spotipy==2.25.1
      - sqlglot==26.16.4
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - typing-inspection==0.4.0
      - urllib3==2.4.0
      - vegafusion==2.0.2
      - vl-convert-python==1.7.0
      - wrapt==1.17.2
